language: rust
sudo: enabled
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
    - cargo build --verbose
    - cargo test --test lib --no-fail-fast --features "json"
    - cargo test --locked  --no-fail-fast --lib
    # - cargo run --example json_to_edn --features "json"
    # - cargo run --example navigate_edn
    # - cargo run --example edn_from_str
    # - cargo run --example struct_from_str
    # - cargo run --example serialize
    # - cargo run --example tokenize_edn
    # - cargo run --example iterator
    # - cargo run --example to_vec
    # - cargo run --example async --features "async"
