name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run unit tests
      run: cargo test --locked  --no-fail-fast --lib
    - name: Run int tests
      run: cargo test --test lib --no-fail-fast --features "json"
    - name: Examples
      run: |
        cargo run --example json_to_edn --features "json"
        cargo run --example navigate_edn
        cargo run --example from_str_edn
        cargo run --example from_str_type
        cargo run --example serialize
        cargo run --example tokenize_edn
        cargo run --example iterator
        cargo run --example to_vec
        cargo run --example async --features "async"
    - name: FMT
      run: |
        rustup component add rustfmt
        cargo fmt -- --check
